In [1]:
# 1. Create 5×5 matrix with values 1–25
import numpy as np
mat = np.arange(1, 26).reshape(5, 5)
print("1:\n", mat)


1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [2]:
# 2. 4×4 Identity matrix
import numpy as np
identity = np.eye(4)
print("2:\n", identity)


2:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
# 3. 1D array from 100 to 200 with step 10
import numpy as np
arr = np.arange(100, 201, 10)
print("3:", arr)

3: [100 110 120 130 140 150 160 170 180 190 200]


In [4]:
# 4. Random 3×3 matrix determinant
import numpy as np
mat = np.random.rand(3, 3)
det = np.linalg.det(mat)
print("4 determinant:", det)

4 determinant: 0.014046022918650864


In [5]:
# 5. 10 random integers between 1 and 100
import numpy as np
rand_ints = np.random.randint(1, 101, 10)
print("5:", rand_ints)

5: [ 13  56  46  57 100  70  82  55  16  95]


In [6]:
# 6. Reshape 1D array size 12 → 3×4 matrix
import numpy as np
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print("6:\n", reshaped)

6:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
# 7. Multiply two 3×3 matrices
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("7:\n", np.matmul(a, b))


7:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [8]:
# 8. Eigenvalues & Eigenvectors of 2×2 matrix
import numpy as np
mat = np.array([[4, 2], [1, 3]])
vals, vecs = np.linalg.eig(mat)
print("8 eigenvalues:", vals)
print("8 eigenvectors:\n", vecs)

8 eigenvalues: [5. 2.]
8 eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [9]:
# 9. 5×5 random matrix, extract diagonal
import numpy as np
mat = np.random.rand(5, 5)
print("9 diagonal:", np.diag(mat))


9 diagonal: [0.90631689 0.36043895 0.64394438 0.47317608 0.91343275]


In [10]:
# 10. Normalize 1D array
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
norm = (arr - arr.min()) / (arr.max() - arr.min())
print("10:", norm)


10: [0.   0.25 0.5  0.75 1.  ]


In [11]:
# 11. Sort array by row & column
import numpy as np
mat = np.array([[9,2,7],[4,6,1],[3,8,5]])
print("11 row sort:\n", np.sort(mat, axis=1))
print("11 col sort:\n", np.sort(mat, axis=0))

11 row sort:
 [[2 7 9]
 [1 4 6]
 [3 5 8]]
11 col sort:
 [[3 2 1]
 [4 6 5]
 [9 8 7]]


In [12]:
# 12. Indices of max and min values
import numpy as np
arr = np.array([10, 25, 5, 30, 15])
print("12 max index:", np.argmax(arr))
print("12 min index:", np.argmin(arr))

12 max index: 3
12 min index: 2


In [13]:

# 13. Flatten 2D array using ravel & flatten
import numpy as np
mat = np.array([[1,2,3],[4,5,6]])
print("13 ravel:", mat.ravel())
print("13 flatten:", mat.flatten())

13 ravel: [1 2 3 4 5 6]
13 flatten: [1 2 3 4 5 6]


In [14]:
# 14. Inverse of 3×3 matrix
import numpy as np
mat = np.array([[1,2,3],[0,1,4],[5,6,0]])
inv = np.linalg.inv(mat)
print("14 inverse:\n", inv)

14 inverse:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [15]:
# 15. Random permutation of numbers 1–10
import numpy as np
perm = np.random.permutation(np.arange(1, 11))
print("15:", perm)

15: [ 3  2 10  1  4  5  8  7  6  9]


In [16]:
# 16. Array from 0 to 20, replace even numbers with -1
import numpy as np
arr = np.arange(21)
arr[arr % 2 == 0] = -1
print("1:", arr)


1: [-1  1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


In [17]:
# 17. Dot product of two arrays
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("2:", np.dot(a, b))


2: 32


In [18]:
# 18. 5×5 random matrix trace
import numpy as np
mat = np.random.randint(1, 10, (5, 5))
print("3:\n", mat, "\nTrace:", np.trace(mat))

3:
 [[7 5 1 5 3]
 [5 3 3 6 1]
 [3 7 7 1 1]
 [9 7 6 7 3]
 [7 5 7 7 6]] 
Trace: 30


In [19]:
# 19. Split 1D array (from 16) into 3 equal parts
import numpy as np
arr = np.arange(16, 25)  # 9 numbers
print("4:", np.split(arr, 3))

4: [array([16, 17, 18]), array([19, 20, 21]), array([22, 23, 24])]


In [20]:
# 20. 3D array mean across axis=0
import numpy as np
arr3d = np.random.randint(1, 10, (3, 3, 3))
print("5:\n", arr3d, "\nMean along axis 0:\n", arr3d.mean(axis=0))

5:
 [[[1 3 9]
  [8 7 2]
  [2 1 6]]

 [[5 5 3]
  [4 7 1]
  [1 5 9]]

 [[6 2 4]
  [3 3 3]
  [4 4 9]]] 
Mean along axis 0:
 [[4.         3.33333333 5.33333333]
 [5.         5.66666667 2.        ]
 [2.33333333 3.33333333 8.        ]]


In [21]:
# 21. Cumulative sum
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("6:", np.cumsum(arr))


6: [ 1  3  6 10 15]


In [22]:
# 22. Upper triangular of 4×4 random matrix
import numpy as np
mat = np.random.randint(1, 10, (4, 4))
print("7:\n", mat, "\nUpper Triangular:\n", np.triu(mat))

7:
 [[8 8 2 9]
 [3 8 5 3]
 [6 2 6 5]
 [1 5 8 9]] 
Upper Triangular:
 [[8 8 2 9]
 [0 8 5 3]
 [0 0 6 5]
 [0 0 0 9]]


In [23]:
# 23. 6×6 checkerboard pattern
import numpy as np
checker = np.indices((6, 6)).sum(axis=0) % 2
print("8:\n", checker)

8:
 [[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [24]:
# 24. 3×3 random matrix element-wise sqrt
mat = np.random.randint(1, 10, (3, 3))
print("9:\n", mat, "\nSqrt:\n", np.sqrt(mat))


9:
 [[3 6 8]
 [9 4 2]
 [2 4 8]] 
Sqrt:
 [[1.73205081 2.44948974 2.82842712]
 [3.         2.         1.41421356]
 [1.41421356 2.         2.82842712]]


In [25]:
# 25. Reverse 1D array of 20 elements (no slicing)
import numpy as np
arr = np.arange(20)
print("10:", np.flip(arr))


10: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [26]:
# 26. Merge arrays vertically and horizontally
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("11 Vertical:\n", np.vstack((a, b)))
print("11 Horizontal:\n", np.hstack((a, b)))


11 Vertical:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
11 Horizontal:
 [[1 2 5 6]
 [3 4 7 8]]


In [27]:
# 27. Row-wise and column-wise sum
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("12 Row sum:", arr.sum(axis=1))
print("12 Column sum:", arr.sum(axis=0))


12 Row sum: [ 6 15]
12 Column sum: [5 7 9]


In [28]:
# 28. Replace NaN with column mean
import numpy as np
arr = np.array([[1, np.nan, 3], [4, 5, np.nan]])
col_mean = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])
print("13:\n", arr)

13:
 [[1. 5. 3.]
 [4. 5. 3.]]


In [29]:
# 29. Cosine similarity
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
cos_sim = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
print("14:", cos_sim)


14: 0.9746318461970762


In [30]:
# 30. Rotate 4×4 array by 90 degrees
import numpy as np
arr = np.arange(16).reshape(4, 4)
print("15 Original:\n", arr)
print("15 Rotated:\n", np.rot90(arr))


15 Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
15 Rotated:
 [[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]


In [31]:
# 31. Structured array (name, age, marks)
import numpy as np
data = np.array([('Alice', 20, 85), ('Bob', 21, 90)],
                dtype=[('name', 'U10'), ('age', 'i4'), ('marks', 'i4')])
print("16:", data)

16: [('Alice', 20, 85) ('Bob', 21, 90)]


In [32]:
# 32. Rank of 3×3 random matrix
import numpy as np
mat = np.random.randint(1, 10, (3, 3))
print("17 Matrix:\n", mat, "\nRank:", np.linalg.matrix_rank(mat))

17 Matrix:
 [[5 9 4]
 [8 3 4]
 [1 4 2]] 
Rank: 3


In [33]:
# 33. Normalize rows of 5×5 matrix
import numpy as np
mat = np.random.randint(1, 10, (5, 5))
normed = mat / np.linalg.norm(mat, axis=1, keepdims=True)
print("18:\n", normed)

18:
 [[0.52827054 0.35218036 0.70436073 0.17609018 0.26413527]
 [0.55874424 0.34921515 0.55874424 0.41905818 0.27937212]
 [0.37573457 0.50097943 0.438357   0.31311215 0.56360186]
 [0.46056619 0.59215653 0.46056619 0.39477102 0.26318068]
 [0.82078268 0.10259784 0.10259784 0.51298918 0.20519567]]


In [34]:
# 34. Check if arrays equal element-wise
import numpy as np
a = np.array([1, 2, 3])
b = np.array([1, 2, 4])
print("19:", np.array_equal(a, b))

19: False


In [35]:
# 35. Histogram of 1000 random numbers
import numpy as np
data = np.random.randn(1000)
hist, bins = np.histogram(data, bins=10)
print("20 Histogram:", hist)
print("20 Bins:", bins)


20 Histogram: [  8  29  92 152 208 224 179  80  24   4]
20 Bins: [-3.0394925  -2.44203686 -1.84458123 -1.24712559 -0.64966995 -0.05221432
  0.54524132  1.14269696  1.7401526   2.33760823  2.93506387]


In [36]:
# 36. Broadcasting (2D + 1D)
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])
print("21:\n", arr2d + arr1d)


21:
 [[11 22 33]
 [14 25 36]]


In [37]:
# 37. Unique values and counts
import numpy as np
arr = np.array([1, 2, 2, 3, 3, 3])
vals, counts = np.unique(arr, return_counts=True)
print("22 Values:", vals, "Counts:", counts)


22 Values: [1 2 3] Counts: [1 2 3]


In [38]:
# 38. Pearson correlation coefficient
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])
print("23:", np.corrcoef(x, y))


23: [[1. 1.]
 [1. 1.]]


In [39]:
# 39. Numerical gradient of 1D array
import numpy as np
arr = np.array([1, 2, 4, 7, 11])
print("24:", np.gradient(arr))


24: [1.  1.5 2.5 3.5 4. ]


In [40]:
# 40. SVD of random 3×3 matrix
import numpy as np
mat = np.random.randint(1, 10, (3, 3))
U, S, Vt = np.linalg.svd(mat)
print("25 Matrix:\n", mat)
print("U:\n", U)
print("S:", S)
print("Vt:\n", Vt)

25 Matrix:
 [[7 9 3]
 [3 8 3]
 [3 6 9]]
U:
 [[-0.64197599  0.55084973  0.53332111]
 [-0.49971074  0.22695392 -0.83593128]
 [-0.58151183 -0.80315409  0.12956655]]
S: [17.6292215   5.68382772  1.97601915]
Vt:
 [[-0.43890195 -0.75241784 -0.49115423]
 [ 0.3742808   0.34384476 -0.86121116]
 [ 0.81687145 -0.56181685  0.13070142]]
